### ISSUE TITLE
More geographies for nearest neighbours

### ISSUE THREAD

**Issue by sebastian-fox** [ropensci/fingertipsR#101]
The `nearest_neighbours()` function currently only allows these area type ids: 101, 102, 201, 202, 152 or 154
This is due to hard coding in the function code as it is currently not possible to source available nearest neighbour geographies interactively through the API. We need to make the more recent geographies available

**Comment by sebastian-fox** [comment]
[Here](https://github.com/ropensci/fingertipsR/blob/master/R/area_types.R#L229) is where the geography coding begins in the function.

These are the codes that have been provided by the fingertips team:
NeighbourTypeId     AreaTypeId
1                              101
1                              102
2                              153
4                              152
6                              154
7                              201
7                              202
9                              166
10                            301
10                            302

**Comment by sebastian-fox** [comment]
For info, I've just been told the Fingertips team has made the table available on the Fingertips test site API, which will go live on Dec 7th. The Live site url will be: https://fingertips.phe.org.uk/api/nearest_neighbour_types

If the code update can wait until after Dec 7th, I'd recommend using this method of checking AreaTypeIds are available and then obtaining the corresponding NeighbourTypeId instead of hard coding them as suggested above

**Comment by sebastian-fox** [comment]
Hi Sam, nice to talk to you just now.
This code *I think* should create the table you need:

```
library(dplyr)

url <- "https://fingertips.phe.org.uk/api/nearest_neighbour_types"

test <- fingertipsR:::get_fingertips_api(url) %>% 
  rename(measure = Name)

df <- test %>% 
  select(NeighbourTypeId, ApplicableAreaTypes) %>% 
  tibble::deframe() %>% 
  bind_rows(.id = "NeighbourTypeId") %>% 
  mutate(NeighbourTypeId = as.integer(NeighbourTypeId)) %>% 
  left_join(test, by = "NeighbourTypeId") %>% 
  dplyr::select(AreaTypeID = Id,
                NeighbourTypeId,
                measure)
  
  ```

**Comment by Samuel-Cutler-PHE** [comment]
Hey Seb, thanks for the call yday, great to finally meet you ! 
I have been going over the code, and inserted the part you kindly wrote into the function with the following which I think specifies the val value based on the dataframe:

val <- if(AreaTypeID %in% df$AreaTypeID) {
                df$NeighbourTypeId[df$AreaTypeID == AreaTypeID]
        } else {
                NA
        }

Interestingly, the CSSN measures are not brought into the table and I had a look at the list and the fields seem to be empty lists so NeighbourTypeId 3, 5 and 8 are missing. 5 and 8 were never specified in the original hard code so don't think these are too much of an issue but might need a catch up on whether 3 is needed: (AreaTypeID == 102 & measure == "CSSN") {
                val <- 3

**Comment by sebastian-fox** [comment]
Thanks for raising this. That's interesting. 
I'll email the fingertips team and copy you in to see if those measures are obsolete on Fingertips now...
