### ISSUE TITLE
fingertips_data (time_period_range) data type error

### ISSUE THREAD

**Issue by daenwaels** [ropensci/fingertipsR#106]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Bug appears when trying to run the _fingertips_data_ function. When binding (**bind_rows**) multiple indicators with different values for **time_period_range** they are coming out as different data types (character - expected type, and logical). 

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# INITIALISE ------------------------------

library(fingertipsR)
library(tibble)

# LOAD FINGERTIPS DATA ------------------------------

ccg.df <-
fingertipsR::fingertips_data(
IndicatorID = c('90987', '93232', '91839') , ### reads chosen indicators
AreaCode = c('E06000003','E06000004','E08000037'), ### reads chosen areas
AreaTypeID = 401)

#>Error: Can't combine `..1$Time period range` <logical> and `..3$Time period range` <character>.
#>Run `rlang::last_error()` to see where the error occurred.
```

**Comment by sebastian-fox** [comment]
Hi @daenwaels - thanks for reporting this. I've updated the code to attempt to fix this bug.
Please could you reinstall the dev version of the package 
```
remotes::install_github("rOpenSci/fingertipsR",
                        build_vignettes = TRUE,
                        dependencies = "suggests")`) 
```
and then test it your end?

If it is ok, please could you close this issue

**Comment by daenwaels** [comment]
Much appreciated thanks @sebastian-fox - all fine on our end.
