### ISSUE TITLE
error when fetching multiple indicators that includes one that have 0 rows returned 

### ISSUE THREAD

**Issue by auhyh** [ropensci/fingertipsR#110]
Hi! 

Thanks for this very useful package. 

I have been using the packaging for various projects, but have come across this small bug from time to time when using the fingertips_data() function. 

For example, 93457 is an indicator that returns no rows, and 20601 is an indicator that returns a data frame. If I fetch both indicators at the same time using fingertips_data(), the code will immediately returns an error as such:

```
Error in `bind_rows()`:
! Can't combine `..1$Time period range` <character> and `..2$Time period range` <logical>.
```

It would be good if the function can skip over the indicators that have zero rows and still return a data frame. Having a list of indicators that have no data to return from in a form of message/warning in the console will also be very helpful, especially in scenarios when working with a long list of indicators.  

```r

fingertips_data(IndicatorID = 93457, AreaTypeID = 302) #indicator returning 0 rows
fingertips_data(IndicatorID = 20601, AreaTypeID = 302)  #normal indicator returning a df 
fingertips_data(IndicatorID = c(20601, 93457), AreaTypeID = 302) #errors when indicator with 0 rows r fetched along with "normal" indicators

```

**Comment by sebastian-fox** [comment]
Hi @auhyh - thanks for the feedback and the message. Which version of the package are you using? `packageVersion("fingertipsR")`?

The current version handles this situation ok. You might need to follow the install instructions in the [README](https://github.com/ropensci/fingertipsR#ropensci) and reinstall the package. Let me know if that helps?

**Comment by auhyh** [comment]
I am indeed using an older version. I have now managed to run the code without errors with the latest version downloaded. Thank you so much for the quick reply!

**Comment by sebastian-fox** [comment]
Great, glad that has worked :)
