### ISSUE TITLE
Error on indicator_update_information when number of indicators is greater than ~250

### ISSUE THREAD

**Issue by DaveJephson** [ropensci/fingertipsR#111]
---

Brief description of the problem

The indicator_update_information function errors when the number of indicators is greater than ~250.

``` r
library(fingertipsR) # for extracting Fingertips indicator data
library(fingertipsRtest) # extract data from Fingertips test site
#> To comply with the Official Statistics code of practice all users of fingertips data from the fingertipsRtest package should not share or publish the data that has not yet been published live on fingertips.

profiles_filter <- c(18,19,26,29)
inds <- indicators(ProfileID=profiles_filter)

indicatorIDs<- unique(inds$IndicatorID)
indicator_date_update <- fingertips_testsite_wrapper(indicator_update_information,
                                                     IndicatorID=indicatorIDs
)
#> No encoding supplied: defaulting to UTF-8.
#> Error: lexical error: invalid char in json text.
#>                                        <!DOCTYPE html PUBLIC "-//W3C//
#>                      (right here) ------^
```

<sup>Created on 2023-01-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sebastian-fox** [comment]
Hi @DaveJephson - thanks for raising this. I've just pushed some changes which should fix the problem.
I think it takes a day or so to update on rOpenSci, so you might need to install it straight from GitHub:

```
remotes::install_github("rOpenSci/fingertipsR",
                        build_vignettes = TRUE,
                        dependencies = "suggests")
```

If this fixes the issue, please could you close it on GitHub?
Thank you :)

**Comment by sebastian-fox** [comment]
Hmmm, so it works on the live site:

```
indicator_date_update <- indicator_update_information(
  IndicatorID = indicatorIDs
)
```

I'm not around tomorrow so I can't look into this then. From your error message it looks like there might be issues with completeness of IndicatorID for indicators available on the test API. Ie, the error message is saying it is trying to bind a character `IID` with an integer `IID`. I need to sign off now, but without digging into it, if an IID isn't available and it is the only record in what the API gives back, it might default to a character.

Are you able to use the live site in at the moment while I don't have time to get to the bottom of it?

**Comment by DaveJephson** [comment]
Thanks for looking into this Seb - it isn't massively urgent so I'm ok to do my onward coding using the results from the live site, which is working for me too.

One thought that your comment prompted was that my selection of indicators was those that are available from the live site, whereas the indicator_update_information function was querying the test site. I changed the code to get all indicators that are available from the test site into my selection and tried the function again, but no luck - the same error was returned.

**Comment by DaveJephson** [comment]
Hi @sebastian-fox, that is strange - I've just run it and got a similar error to before:

Error in `dplyr::bind_rows()`:
! Can't combine `..1$IID` <character> and `..1558$IID` <integer>

We're not actively using this code at the moment so not top priority to fix, but still seems to be behaving oddly!

**Comment by sebastian-fox** [comment]
No problem Dave - I don't want to side track you from what you're doing atm.
I get your exact error if I install an earlier version of the package 48a5913e8cace4e494f5dcb192f38e8b32f1b671 - but when I update it to the latest version I don't get the error anymore

```
remotes::install_github("rOpenSci/fingertipsR",
                        build_vignettes = TRUE,
                        dependencies = "suggests")
```

No rush to test it but I'm hoping it is resolved 🤞

**Comment by DaveJephson** [comment]
Aha - that has sorted it! I'll close the issue but let you know if anything similar happens in the future. Thanks!

**Comment by sebastian-fox** [comment]
Super, thank you :)
