### ISSUE TITLE
nearest_neighbours function - Error: lexical error: 

### ISSUE THREAD

**Issue by RichFlint** [ropensci/fingertipsR#114]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
receive the following error when running the nearest_neighbours function

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html>  <html lang="en
                     (right here) ------^

```r
# insert reprex here
```

**Comment by sebastian-fox** [comment]
Hi @RichFlint  - thanks for reporting this. We've identified the issue and are trying to resolve it.
Note, it also affects `nearest_neighbour_areatypeids()`

**Comment by sebastian-fox** [comment]
Hi @RichFlint - looks like it has been fixed now. When you get a chance, please could you check this and then close this issue if it is ok?
Many thanks
