### ISSUE TITLE
Repo description and topics to review

### ISSUE THREAD

**Issue by maelle** [ropensci/fingertipsR#48]
:wave: @sebastian-fox!

I've updated the repo description and topics to increase its discoverability, see below.

![image](https://user-images.githubusercontent.com/8360597/40099485-7f7744b0-58e0-11e8-83dd-8147aa3589d8.png)

Of course feel free to update them until you like them. The topics and description will be useful not only for discovery via GitHub but also via rOpenSci registry which will use them.

Thank you! 😺

**Comment by sebastian-fox** [comment]
thanks @maelle - that seems really usful. Is there anything I need to do with this or can I close the issue?

**Comment by maelle** [comment]
If you don't want to change the topics you can indeed just close the issue ☺

**Comment by sebastian-fox** [comment]
Great, thank you. I'm just adding a few others now. Also trying to work out how you search by tags on GitHub. Thanks again

**Comment by maelle** [comment]
For info in the near future I plan to add "r" and "rstats" to all rOpenSci packages.

**Comment by maelle** [comment]
If you click on a topic you will see other repos, i actually saw one for fingertip and advertised your pkg!

**Comment by sebastian-fox** [comment]
Cool - thanks! GitHub has so much to it!

**Comment by maelle** [comment]
By the way three tips (pun unintended) for [your profile](https://github.com/sebastian-fox)  and I'll stop

* I think GitHub profiles look more legit with a name and an avatar (any picture, doesn't need to be a face)

* you are a member of the rOpenSci organization but by default membership to organizations are hidden. You can make it public [see this page](https://help.github.com/articles/publicizing-or-hiding-organization-membership/).

* although the package repo now lives here you can pin it to your profile see [this page](https://help.github.com/articles/pinning-repositories-to-your-profile/).

Now I'll see myself out 👋

**Comment by sebastian-fox** [comment]
Hehe - stay! These things would have taken me years to work out. I need all the help I can get :)

**Comment by sebastian-fox** [comment]
Thanks - all done :)
