### ISSUE TITLE
Error message when using fingertips_data command:  sysdata.rdb

### ISSUE THREAD

**Issue by Cameronr99** [ropensci/fingertipsR#50]
Hi

I'm getting an error message when using the fingertips_data command:

 fingertips_data(,,,19)
Error in date_names_lang(date_names) : 
  cannot open file '~/R/win-library/3.4/readr/R/sysdata.rdb': No such file or directory

I've tried reinstalling readr already.

Grateful for any help = I'm new to R :-)

Thanks
Cameron Russell
Worcestershire County Council

**Comment by sebastian-fox** [comment]
Hi @Cameronr99 , I'm not entirely sure as looking at your directory path your R is configured slightly differently to mine. I've just read [this](https://github.com/tidyverse/tidyverse/issues/46) discussion and I think you might have something similar going on. My guess is that, for some reason, your `readr` isn't installed in the place R looks for it when that function is running.

I realise you said you've reinstalled `readr` already. Have you tried uninstalling it then installing it again? If not, this is what the last comment said worked for him. Try:
```
remove.packages("readr")
install.packages("readr")
```
Hopefully that will put it in the right place. Let me know how you get on.

Also, for info, `fingertips_data(ProfileID = 19)` does the same thing as what you've written and is more readable. I wouldn't normally comment on people's code, but you said you are new to R so I thought that might be helpful.

Seb

**Comment by Cameronr99** [comment]
Hi @sebastian-fox 

That worked, thank you!

Happy for you to comment on the code, I thought I needed the commas to denote null values - your suggestion is appreciated. I've just been on the PHE workshop so far so am a real novice.

Cameron

**Comment by sebastian-fox** [comment]
Great - very pleased that's worked :)
Enjoy `fingertipsR` - do let us know if you do anything exciting with it
Seb
