### ISSUE TITLE
fingertips_data function returns error

### ISSUE THREAD

**Issue by nujcharee** [ropensci/fingertipsR#57]
When trying sample code in vignette 

```
indid <- 90362
df <- fingertips_data(IndicatorID = indid)
head(df)
```
I got following error.
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'Compared to subnational parent value or percentiles' not found.
Many thanks

**Comment by nujcharee** [comment]
Forgot to mention im on R 3.4.4

**Comment by nujcharee** [comment]
Ahh that explained it :) Its ‘0.1.8’ and I just installed from CRAN....

**Comment by nujcharee** [comment]
All working now thank you so much @sebastian-fox

**Comment by sebastian-fox** [comment]
Thanks @nujcharee  glad it is working :+1:
