### ISSUE TITLE
Problem downloading data for certain indicators

### ISSUE THREAD

**Issue by Albluca** [ropensci/fingertipsR#61]
Hi, I'm having some issues with fingertips_data(). It seems that the data associated with certain indicators are not being downloaded. e.g.

df <- fingertips_data(ProfileID = 92) # Cancer Services

returns a data frame with 0 rows to me. While for example 

df <- fingertips_data(ProfileID = 91) # Suicide Prevention Profile

works file and returns a data frame with 56362 rows. Any idea why that is the case? Thanks!

**Comment by sebastian-fox** [comment]
Hi @Albluca - thanks for the message. the `fingertips_data` function defaults to `AreaTypeID = 102`. Where 102 is County and Unitary Authorities. The Cancer Services profile doesn't have data for this AreaTypeID. You can look on the [website](https://fingertips.phe.org.uk/profile/cancerservices/data#page/0/gid/1938132830/pat/152/par/E38000022/ati/7/are/L81131) for what geographies are available and then use the `area_types()` function to work out the correct AreaTypeID that you want. 

This will return data for CCG unchanged plus old 2017:
```
df <- fingertips_data(ProfileID = 92, AreaTypeID = 153)
```

To see what specific indicators are available at each area type, you can use the `indicator_areatypes()` function

**Comment by Albluca** [comment]
Hi @sebastian-fox Thanks for the explanation!
