### ISSUE TITLE
deprivation_decile not working for GPs (AreaTypeID == 7)

### ISSUE THREAD

**Issue by prockenschaub** [ropensci/fingertipsR#62]
Running `deprivation_decile(AreaTypeID = 7, Year = 2010)` (or any other year) returns an empty data.frame. 

The function itself is looking for `if (AreaTypeID == 7) { IndicatorID <- 338; ProfileID <- 20}`, which according to the output of function `indicators()` does not seem to exist. The correct IndicatorID appears to be 91872.

This issue occurred in the current CRAN version 0.2.0.

**Comment by sebastian-fox** [comment]
Thanks for reporting this @prockenschaub 
I've updated the development version of the package, so you can install this if you want the function to work now. Note, there is now only 2015 data available for Index of Multiple Deprivation for GPs on Fingertips.
