### ISSUE TITLE
duplicate data when using ProfileID with fingertips_data()

### ISSUE THREAD

**Issue by SteveSpreadborough** [ropensci/fingertipsR#63]
When passing a vector of indicator IDs and profile IDs some of the indicators come back with duplicate data with different indicator names, looks like it's extracting data from different profiles. From the below code, the table "withProfileID" has a number of indicators that have more than 1 indicator name, whereas the "withoutProfileID" table doesn't

#install.packages("devtools")
devtools::install_github("rOpenSci/fingertipsR",
                         build_vignettes = TRUE,
                         dependencies = TRUE)
library(fingertipsR)
library(dplyr)

#IndicatorIDs
IndsID <- c(91414, 92544, 92432, 92904, 90244, 90245, 30315, 30314, 91361, 91818, 
            30101, 30311, 91367, 90791, 92896, 92324, 40501, 40502, 90834, 22001)

#ProfileIDs
ProfIDs <- c(19, 19, 19, 87, 19, 19, 19, 19, 19, 30, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19)

#Using ProfileID
ftdata <- fingertips_data(IndicatorID = IndsID, ProfileID = ProfIDs)

withProfileID <- ftdata %>%
  select(IndicatorID, IndicatorName) %>%
  unique() %>%
  arrange(IndicatorID) %>%
  group_by(IndicatorID) %>%
  summarise(NumberNames = n()) %>%
  filter(NumberNames > 1)

#Without ProfileID
ftdata2 <- fingertips_data(IndicatorID = IndsID)

withoutProfileID <- ftdata2 %>%
  select(IndicatorID, IndicatorName) %>%
  unique() %>%
  arrange(IndicatorID) %>%
  group_by(IndicatorID) %>%
  summarise(NumberNames = n()) %>%
  filter(NumberNames > 1)

**Comment by sebastian-fox** [comment]
Thanks @SteveSpreadborough - this should be resolved now in the latest dev version

**Comment by SteveSpreadborough** [comment]
great, thanks @sebastian-fox
