### ISSUE TITLE
Indicator name for indicators 92962 and 93012

### ISSUE THREAD

**Issue by DavidNphe** [ropensci/fingertipsR#66]
These indicators from the Public Health Dashboard profile (profile ID = 141) have exactly the same "IndicatorName" when accessed through fingertipsR: "Deaths in treatment, mortality ratio".

92962 relates to deaths in drug treatment
93012 relates to deaths in alcohol treatment

It would be helpful if the indicator name reflected this.

**Comment by sebastian-fox** [comment]
Thanks for reporting this. Unfortunately, these are the `IndicatorName`s for those indicators as displayed on the website. Unless we want the name to change on the website then we can't change the `IndicatorName` provided by the package.

I recommend using `indicators(ProfileID = 141)` to join the `DomainName` to your indicators to differentiate between them.

**Comment by PHEleighdowd** [comment]
Hi David, sorry about this. I've updated the indicator names in FPM to reflect that one is for drug treatment, the other for alcohol treatment. I've pushed the update through to the test site, and I am going to speak to Doris this afternoon to see if we can get this update pulled through for the update on the 5th.

Cheers

**Comment by sebastian-fox** [comment]
Super - thanks @PHEleighdowd . Can I close this issue @DavidNphe ?

**Comment by DavidNphe** [comment]
> Super - thanks @PHEleighdowd . Can I close this issue @DavidNphe ?

Yes, of course. I am, as always, impressed by LD's swift response.
