### ISSUE TITLE
indicator_metadata() missing data

### ISSUE THREAD

**Issue by MarkParker451** [ropensci/fingertipsR#67]
I'm getting the following error when I use indicator_metadata(). The result I get is missing the Polarity column. There's a column called Specific Rationale between Indicator Content and Unit, which I can't see referred to in the code - is that column new?

` 
s <- indicator_metadata(IndicatorID = 22401, ProfileID = 130)
Warning: 1 parsing failure.
row col   expected     actual         file
  1  -- 31 columns 32 columns <raw vector>

Warning message:
Unnamed `col_types` should have the same length as `col_names`. Using smaller of the two. 
 `

**Comment by sebastian-fox** [comment]
Hi @MarkParker451 - thanks for reporting this. This should be fixed in the development version of the package. Let me know if so and I can close the issue. Otherwise, I'll look into it

**Comment by MarkParker451** [comment]
@sebastian-fox Many thanks for the quick response. Yes, that now works.
Thanks.
