### ISSUE TITLE
fingertips_data not returning data for all indicators at MSOA Level (Local Health Data)

### ISSUE THREAD

**Issue by stephshadwell** [ropensci/fingertipsR#71]
i am trying to get some data from fingertipsR for local health data. I have ran this code prior to the update to the new version of fingertipsR (0.2.3) without any issues. I have noticed today that when i filter for the england data, 4 out of 5 of the indicators do not have a value, and i only get MSOA data for indicatorID 93267. I have checked the downloads from local health, and all 5 indicators have a value, and there is MSOA data for all 5 indicators as well. See code below

`inds <- c(93267, 93229, 93232, 93234, 93259)

#get data
lhdata <- fingertips_data(ProfileID = 143, AreaTypeID = 3)

#filter lhdata to only have required indicators
lhdata <- lhdata %>%
  filter(IndicatorID %in% inds)

#create eng values
england <- lhdata %>%
  filter(AreaType == "England") %>%
  select(IndicatorID, Value) %>%
  rename(England_Value = Value)

#filter for MSOA AreaType
lhdata <- lhdata %>%
  filter(AreaType == "MSOA") %>%
  select(-CategoryType, -Category, -LowerCI99.8limit, -UpperCI99.8limit)`

**Comment by sebastian-fox** [comment]
Hi @stephshadwell - my understanding is that Local Health data has been removed this month. It should be back next month...

**Comment by stephshadwell** [comment]
thanks seb :-)
