### ISSUE TITLE
Issue loading fingertipsR

### ISSUE THREAD

**Issue by nehakas** [ropensci/fingertipsR#78]
Hi all,

Not sure why I am getting this error. I tried updating the R version.
```
 library(fingertipsR)
Error: package or namespace load failed for ‘fingertipsR’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘httpuv’
```

Thanks.

**Comment by sebastian-fox** [comment]
Hi @nehakas, thanks for your message.
The end of your error message says `there is no package called 'httpuv'` - that means that this package isn't available in your library of packages. It may have previously been there, but for one reason or another been removed.

Could you try restarting R/RStudio and then try `install.packages("httpuv")`?

You may have a few more similar errors (I seem to have them in batches - not related to `fingertipsR`). If you work through installing all the missing packages then get in touch if the errors still persist.

If this solves the issue, please could you close this issue?

Thank you

**Comment by nehakas** [comment]
Thanks Sebastian! It is solved!
