### ISSUE TITLE
Amount of data accessible with this pkg?

### ISSUE THREAD

**Issue by sckott** [ropensci/fingertipsR#80]
👋  as part of preparing an ropensci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg?  And/or whatever metric is most relevant for this data?

thanks!

**Comment by sebastian-fox** [comment]
Hi @sckott - thanks for the message. This package offers data on indicators about public health in England. Today the package has data on slightly more than 1,500 indicators. Most indicators are presented at multiple levels of geography, for multiple time periods, some are for multiple age bands and for both sexes. 

There are almost 23 million records in the database they come from. 

Happy to answer more questions if you have any

**Comment by sckott** [comment]
thanks very much. that'll do it.
