### ISSUE TITLE
Issue with deprivation_decile function

### ISSUE THREAD

**Issue by matthew-francis** [ropensci/fingertipsR#81]
Running code deprivation_decile(AreaTypeID = 102, Year=2015) returns an empty dataframe (0 obs. of 3 variables).

**Comment by sebastian-fox** [comment]
Thanks for reporting this @matthew-francis - I think this was fixed in a recent release of the package. Could you check your version and if it isn't 0.2.9 could you reinstall it? If this resolves the issue could you close if please? Otherwise, please let me know

**Comment by matthew-francis** [comment]
Just needed to reinstall fingertipsR
