### ISSUE TITLE
pkgdown site fails to build

### ISSUE THREAD

**Issue by jeroen** [ropensci/fingertipsR#84]
See log here: https://dev.ropensci.org/job/fingertipsR/lastBuild/console

**Comment by sebastian-fox** [comment]
Thanks for this @jeroen - it's failing on a vignette I have specified not to build in .Rbuildignore - do you know/can you point me towards guidance on how to stop this from building on Jenkins?

**Comment by jeroen** [comment]
pkgdown builds all Rmd files under vignettes in the git source, it doesn't filter buildignore. Why is file in vignettes if you don't want to build it?

**Comment by sebastian-fox** [comment]
We were using that location to collaborate on a paper about the package. I can move it elsewhere, though I'm not sure where is appropriate. Is there a folder in a package that I can store it in that won't cause pkgdown to fall over? Or should I move it to a separate repo entirely?

**Comment by jeroen** [comment]
Yeah if you don't want to actually execute the code in the paper, maybe move it to a new directory `paper` that you add to `.gitignore`. Or maybe see if you can fix it so that the code in the paper works?

**Comment by sebastian-fox** [comment]
Thanks for the tips - I think this is ok now? Can I close the issue?

**Comment by jeroen** [comment]
Yes thanks!

**Comment by jeroen** [comment]
Can you also add the docs url to your DESCRIPTION file? https://docs.ropensci.org/fingertipsR/
