### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by MikeJohnPage** [ropensci/fingertipsR#93]
Are you aware this package has now been removed from CRAN?

https://cran.r-project.org/web/packages/fingertipsR/index.html

**Comment by sebastian-fox** [comment]
Hi @MikeJohnPage  - thanks for writing. Yes, I am aware. I have updated the [README](https://github.com/ropensci/fingertipsR) file reflecting how users should now install the package. Please let me know if you have trouble with this method of installing.

**Comment by MikeJohnPage** [comment]
Ah yeah i've just noticed the commit - apologies I didn't spot this early. Thought it was just better to flag just in case 👍

**Comment by sebastian-fox** [comment]
No problem - thanks for getting in touch :)
