### ISSUE TITLE
unsychronised data between fingertipsR and the PHOF fingertips site

### ISSUE THREAD

**Issue by stevecrawshaw** [ropensci/fingertipsR#97]
---

It looks like the data on fingertipsR is not in sync with that  [published on the website e.g.](https://fingertips.phe.org.uk/search/air%20quality#page/4/gid/1/pat/6/ati/102/are/E06000023/iid/30101/age/230/sex/4/cid/4/tbm/1/page-options/ovw-do-2)

has 2019 data

if I use the fingertipsR API, the latest year is 2018

```r
library(tidyverse)
library(fingertipsR)
indid <- 30101
fingertips_data(IndicatorID = indid, AreaTypeID = 202) %>% 
    filter(AreaName %in% c("South West region", "England", "Bristol")) %>% 
    transmute(Area = AreaName, Year = as.integer(Timeperiod), Value) %>% 
   select(Year) %>% 
    filter(Year == max(Year))
```
please advise..

**Comment by sebastian-fox** [comment]
Hi @stevecrawshaw 

Thanks for the message. You're right that the API shouldn't be out of sync with the website. When it is it is usually a question of `AreaTypeID`. This is the case for your query. See below:

```
library(fingertipsR)
library(dplyr)

indid <- 30101

aq <- fingertips_data(IndicatorID = indid, AreaTypeID = 202) %>% 
  filter(AreaName %in% c("South West region", "England", "Bristol")) %>% 
  transmute(Area = AreaName, Year = as.integer(Timeperiod), Value) %>% 
  select(Year) %>% 
  filter(Year == max(Year))

print(aq)

aq_pre_2019 <- fingertips_data(IndicatorID = indid, AreaTypeID = 102) %>% 
  filter(AreaName %in% c("South West region", "England", "Bristol")) %>% 
  transmute(Area = AreaName, Year = as.integer(Timeperiod), Value) %>% 
  select(Year) %>% 
  filter(Year == max(Year))

print(aq_pre_2019)
```

I can't answer why `AreaTypeID = 202` doesn't go up to 2019. You'd need to contact [the Fingertips team](mailto:profilefeedback@phe.gov.uk) if you want that answer.

Does this make sense? If so, please could you close this issue.
Thank you

**Comment by stevecrawshaw** [comment]
Thanks Sebastian for your quick reply, it looks like its something to do with timelines of boundary changes:

  AreaTypeID                               AreaTypeName
1        102    Upper tier local authorities (pre 4/19)
2        202 Upper tier local authorities (4/19 - 3/20)

as you say, the data is timely for the AreaTypeID 102. Will close now, thanks.
